### PR TITLE
Add js init api (fixes #27)

### LINKED ISSUE #27: Add API to initialize table anytime
Hello @djk2 I'd like to propose a small change to the JS code of the project. Right now, the table initialization is performed by an anonymous function that is called when document is ready. See line 3 of django_tables2_column_shifter.js. This function does various stuff but everything is inside the anonymous function so it isn't visible outside.

My proposal would be to create a *named* function (maybe named something like `$.django_tables2_column_shifter_init`) that would contain all the stuff that this anonymous function does. This named function will be added to the API of this project so other client code can call it (similar to `$.django_tables2_column_shifter_hidden`). The `$(document).ready` will only call this named function.

So nothing really will change beyond the addition of 1 more function to the API of the js of this project. 

Why is it needed? If we want to use frameworks like unpoly (https://unpoly.com/) that transition between pages *without* full page loads, the `$(document).ready` event is *not* fired when doing page transitions. That results to the table not initializing. To fix that, unpoly has a way to run arbitrary javascript when the DOM "sees" a specific element. So in this case, when the DOM sees the `.column-shifter-container` element it will run the `$.django_tables2_column_shifter_init()` function I mentioned above and the table will initialize.

I'd be happy to provide a PR if you agree with this approach (or you can do it yourself if you want to name/refactor things your way).

Kind regards,
Serafeim

### PR DESCRIPTION
**Pull request by spapas**
This adds an API function called `$.django_tables2_column_shifter_init` that can be used to initialize the column shifter tables any time and specifically when a framework like unpoly or htmx is used. This function is also called on the page ready event to keep the existing behavior.

Notice that I've compressed the js source using uglify-js with the following command: uglifyjs --compress --mangle -- django_tables2_column_shifter.js > django_tables2_column_shifter.min.js; if you are using a different util then I recommend re-compressing it. I've also bubped the verwsion and added the changelog so this should beis ready for releasing to pypi.

The above should resolve #27

### CODE REVIEW

**Comment by spapas** [comment]
Hey @djk2 it seems that github actions no longer support python 3.6! Also tox.ini has tests for some very old and unsupported stuff. I'll try to remove non-needed things and provide a new PR that fixes this.

**Comment by djk2** [comment]
Hi. Today I released new version 2.1.0 where I added support for django 4.0 and 4.2  + python 3.10 
New version was already merged to `master` 
Can you merge (rebase) `master` to your PR?  

I prefer to keep support for old (or very old) versions of python / django as long it is possible. 
Some companies are using my lib in very legacy code.

**Comment by spapas** [comment]
Excellent, I'll rebase with master thank you!

**Comment by spapas** [comment]
Everything seems ok !

**Pull request merged**
